# Generated by Django 6.0.7 on 2026-07-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('income_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imei_code', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('is_sold', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
